# Generated by Django 5.2.8 on 2026-03-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epelleApp', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
